=== vivekyaramada/PRP/prp-mq/src/main/resources/configuration/flatworm-data-description_1_0.dtd
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by James Turner (Benefit Systems, Inc) -->
<!--
     DTD for the Flatworm Data Exchange Tool, Version 1.0

     To support validation of your configuration file, include the following
     DOCTYPE element at the beginning (after the "xml" declaration):

     <!DOCTYPE flatworm-data-description PUBLIC
       "-//Black Bear Software//DTD Flatworm Data Description 1.1//EN"
       "http://www.blackbear.com/dtds/flatworm-data-description_1_0.dtd">

     $Id: flatworm-data-description_1_0.dtd,v 1.5 2009/12/07 01:19:24 dderry Exp $
-->
<!-- ========== Defined Types ============================================= -->
<!ENTITY % BeanClass "CDATA">
<!ENTITY % Integer "CDATA">
<!ELEMENT file-format (converter+, record+)>
<!ATTLIST file-format
id ID #IMPLIED
>
<!ELEMENT converter EMPTY>
<!ATTLIST converter name CDATA #REQUIRED>
<!ATTLIST converter class CDATA #REQUIRED>
<!ATTLIST converter method CDATA #REQUIRED>
<!ATTLIST converter return-type CDATA #REQUIRED>

<!ELEMENT record (record-ident?, record-definition)>
<!ATTLIST record name CDATA #REQUIRED>
<!ELEMENT record-ident (length-ident | field-ident)>
<!ELEMENT length-ident EMPTY>
<!ATTLIST length-ident
minlength %Integer; #REQUIRED
maxlength %Integer; #REQUIRED
>
<!ELEMENT field-ident (match-string+)>
<!ATTLIST field-ident
field-start %Integer; #REQUIRED
field-length %Integer; #REQUIRED
>
<!ELEMENT match-string (#PCDATA)>
<!ELEMENT record-definition (bean+, line+)>
<!ELEMENT bean EMPTY>
<!ATTLIST bean
id ID #IMPLIED
name CDATA #REQUIRED
class %BeanClass; #REQUIRED
>
<!ELEMENT line (record-element+ | segment-element+)+>
<!ELEMENT record-element (conversion-option*)>
<!ATTLIST record-element
id ID #IMPLIED
start %Integer; #IMPLIED
end %Integer; #IMPLIED
length %Integer; #IMPLIED
beanref CDATA #IMPLIED
type CDATA #IMPLIED
>
<!ELEMENT segment-element (field-ident, (record-element+ | segment-element+)+)>
<!ATTLIST segment-element
name CDATA #IMPLIED
minCount %Integer; #REQUIRED
maxCount %Integer; #REQUIRED
parent-beanref CDATA #IMPLIED
addMethod CDATA #IMPLIED
beanref CDATA #IMPLIED
cardinality-mode CDATA #IMPLIED
>
<!ELEMENT conversion-option EMPTY>
<!ATTLIST conversion-option
name CDATA #REQUIRED
value CDATA #REQUIRED
>

=== vivekyaramada/PRP/prp-mq/src/main/resources/configuration/payment-flatworm-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE file-format SYSTEM
        "/Users/jarsen/IdeaProjects/PRP-MQ/src/main/resources/configuration/flatworm-data-description_1_0.dtd">
<file-format>
    <converter name="char" class="com.blackbear.flatworm.converters.CoreConverters" method="convertChar"
               return-type="java.lang.String"/>
    <converter name="decimal" class="com.blackbear.flatworm.converters.CoreConverters" method="convertDecimal"
               return-type="java.lang.Double"/>
    <converter name="integer" class="com.blackbear.flatworm.converters.CoreConverters" method="convertInteger"
               return-type="java.lang.Integer"/>
    <converter name="date" class="com.blackbear.flatworm.converters.CoreConverters" method="convertDate"
               return-type="java.sql.Date"/>

    <record name="application">
        <record-ident>
            <field-ident field-start="0" field-length="4">
                <match-string>APP2</match-string>
            </field-ident>
        </record-ident>
        <record-definition>
            <bean name="application" class="gov.hhs.cms.prp.entity.PrpApplicationEntity"/>
            <line>
                <record-element length="4"/> <!-- Segment ID -->
                <record-element length="10" beanref="application.applPsId" type="integer"/>
                <record-element length="10" beanref="application.applId" type="integer"/>
                <record-element length="8" beanref="application.applStartDate" type="date">
                    <conversion-option name="format" value="yyyyMMdd"/>
                </record-element>
                <record-element length="8" beanref="application.applEndDate" type="date">
                    <conversion-option name="format" value="yyyyMMdd"/>
                </record-element>
                <record-element length="2" beanref="application.applStatus" type="char"/>
                <record-element length="1" beanref="application.applTransMethod" type="char"/>
                <record-element length="1" beanref="application.applExtension" type="char"/>
                <record-element length="1" beanref="application.applRetlistSw" type="char"/>
                <record-element length="30" beanref="application.applPsCompany" type="char">
                    <conversion-option name="pad-character" value=" "/>
                    <conversion-option name="justify" value="left"/>
                </record-element>
                <record-element length="8" beanref="application.applRcncltnDate" type="date">
                    <conversion-option name="format" value="yyyyMMdd"/>
                </record-element>
                <record-element length="1"/> <!-- Reconciliation date update indicator -->
                <record-element length="8" beanref="application.applStp4Dt" type="date">
                    <conversion-option name="format" value="yyyyMMdd"/>
                </record-element>
                <record-element length="1"/> <!-- Step 4 date update indicator -->
                <record-element length="27"/> <!-- Filler -->
            </line>
        </record-definition>
    </record>
    <record name="planOption">
        <record-ident>
            <field-ident field-start="0" field-length="4">
                <match-string>OPT2</match-string>
            </field-ident>
        </record-ident>
        <record-definition>
            <bean name="planOption" class="gov.hhs.cms.prp.entity.PrpPlanOptionsEntity"/>
            <line>
                <record-element length="4"/> <!-- Segment ID -->
                <record-element length="10" beanref="planOption.planNdmVendor" type="char">
                    <conversion-option name="pad-character" value="0"/>
                    <conversion-option name="justify" value="right"/>
                </record-element>
                <record-element length="10" beanref="planOption.planApplId" type="integer"/>
                <record-element length="20" beanref="planOption.planGroupNumber" type="char">
                    <conversion-option name="pad-character" value=" "/>
                    <conversion-option name="justify" value="left"/>
                </record-element>
                <record-element length="1" beanref="planOption.planSubmMethod" type="char"/>
                <record-element length="1" beanref="planOption.planRespMethod" type="char"/>
                <record-element length="1" beanref="planOption.planNotifMethod" type="char"/>
                <record-element length="4" beanref="planOption.planVdsaPlanNum" type="char" />
                <record-element length="9" beanref="planOption.planVdsaMirId" type="char">
                    <conversion-option name="pad-character" value="0"/>
                    <conversion-option name="justify" value="right"/>
                </record-element>
                <record-element length="10"/> <!-- Filler -->
            </line>
        </record-definition>
    </record>

</file-format>

=== vivekyaramada/PRP/prp-mq/src/main/resources/configuration/simple-example.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE file-format SYSTEM "/Users/jarsen/IdeaProjects/PRP/prp-mq/src/main/resources/configuration/flatworm-data-description_1_0.dtd">
<file-format>
    <converter name="char" class="com.blackbear.flatworm.converters.CoreConverters" method="convertChar" return-type="java.lang.String" />
    <converter name="decimal" class="com.blackbear.flatworm.converters.CoreConverters" method="convertDecimal" return-type="java.lang.Double" />
    <record name="newhire">
        <record-ident>
            <field-ident field-start="0" field-length="2">
                <match-string>NH</match-string>
            </field-ident>
        </record-ident>
        <record-definition>
            <bean name="employee" class="gov.hhs.cms.prp.messaging.entitytmp.Employee" />
            <line>
                <record-element length="2" />
                <record-element length="15" beanref="employee.firstName" type="char">
                    <conversion-option name="justify" value="left" />
                </record-element>
                <record-element length="15" beanref="employee.lastName" type="char">
                    <conversion-option name="justify" value="left" />
                </record-element>
                <record-element length="1" beanref="employee.gender" type="char" />
                <record-element length="11" beanref="employee.ssn" type="char">
                    <conversion-option name="strip-chars" value="non-numeric" />
                </record-element>
                <record-element length="10" beanref="employee.salary" type="decimal">
                    <conversion-option name="decimal-places" value="2" />
                    <conversion-option name="decimal-implied" value="true" />
                    <conversion-option name="pad-character" value="0" />
                    <conversion-option name="justify" value="right" />
                </record-element>

            </line>
        </record-definition>
    </record>
</file-format>
